// <auto-generated />
namespace EniProjetMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migr_img : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr_img));
        
        string IMigrationMetadata.Id
        {
            get { return "201805170929355_migr_img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
